// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8oDaT12l6cutBosE_bG191Oy6JxUGN7E',
    appId: '1:420049836351:web:c2da8f4cf7beb3b05f5b8a',
    messagingSenderId: '420049836351',
    projectId: 'helloworld-46e7e',
    authDomain: 'helloworld-46e7e.firebaseapp.com',
    storageBucket: 'helloworld-46e7e.firebasestorage.app',
    measurementId: 'G-TCZT0FLE79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAj5LEPa7zZmN0vyZ2iMBTYWOClwOivBY',
    appId: '1:420049836351:android:0a675b19c67b8cf65f5b8a',
    messagingSenderId: '420049836351',
    projectId: 'helloworld-46e7e',
    storageBucket: 'helloworld-46e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW32lyLw7VDnDdnWzlrMTAP9WO1H04CVU',
    appId: '1:420049836351:ios:8c3ea974b4ed1e505f5b8a',
    messagingSenderId: '420049836351',
    projectId: 'helloworld-46e7e',
    storageBucket: 'helloworld-46e7e.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW32lyLw7VDnDdnWzlrMTAP9WO1H04CVU',
    appId: '1:420049836351:ios:8c3ea974b4ed1e505f5b8a',
    messagingSenderId: '420049836351',
    projectId: 'helloworld-46e7e',
    storageBucket: 'helloworld-46e7e.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8oDaT12l6cutBosE_bG191Oy6JxUGN7E',
    appId: '1:420049836351:web:0d986273a03433c75f5b8a',
    messagingSenderId: '420049836351',
    projectId: 'helloworld-46e7e',
    authDomain: 'helloworld-46e7e.firebaseapp.com',
    storageBucket: 'helloworld-46e7e.firebasestorage.app',
    measurementId: 'G-5WW4DDG89T',
  );

}